script

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -43,134 +43,149 @@ branding:
 runs:
   using: "composite"
   steps:
-    - name: Set translation paths
-      id: translation-paths
-      shell: bash
-      run: |
-        > paths.txt
-        translations_path="${{ inputs.translations_path }}"
-        while IFS= read -r path; do
-          path=$(echo "$path" | xargs)
-          if [ -n "$path" ]; then
-            echo "./${path}/${{ inputs.base_lang }}/**/*.${{ inputs.file_format }}" >> paths.txt
-          fi
-        done <<< "$translations_path"
+  - name: Run Go Action
+    env:
+      K1: ${{ inputs.additional_params }}
+      K2: ${{ inputs.project_id }}
+      K3: ${{ inputs.base_lang }}
+    shell: bash
+    run: |
+      "${{ github.action_path }}/bin/demoscript"
 
-    - name: Get changed files
-      id: changed-files
-      uses: tj-actions/changed-files@v45
-      with:
-        files_from_source_file: paths.txt
-        separator: ','
+  - name: Verify GITHUB_OUTPUT
+    shell: bash
+    run: |
+      echo "Contents of GITHUB_OUTPUT file:"
+      cat $GITHUB_OUTPUT
 
-    - name: Check if this is the first run on the branch
-      if: steps.changed-files.outputs.any_changed == 'false'
-      id: check-first-run
-      shell: bash
-      run: |
-        set -e
+    # - name: Set translation paths
+    #   id: translation-paths
+    #   shell: bash
+    #   run: |
+    #     > paths.txt
+    #     translations_path="${{ inputs.translations_path }}"
+    #     while IFS= read -r path; do
+    #       path=$(echo "$path" | xargs)
+    #       if [ -n "$path" ]; then
+    #         echo "./${path}/${{ inputs.base_lang }}/**/*.${{ inputs.file_format }}" >> paths.txt
+    #       fi
+    #     done <<< "$translations_path"
 
-        if git rev-parse "refs/tags/lokalise-upload-complete" >/dev/null 2>&1; then
-          echo "first_run=false" >> $GITHUB_OUTPUT
-        else
-          echo "first_run=true" >> $GITHUB_OUTPUT
-        fi
+    # - name: Get changed files
+    #   id: changed-files
+    #   uses: tj-actions/changed-files@v45
+    #   with:
+    #     files_from_source_file: paths.txt
+    #     separator: ','
 
-    - name: Find all translation files
-      if: steps.changed-files.outputs.any_changed == 'false' && steps.check-first-run.outputs.first_run == 'true'
-      id: find-files
-      shell: bash
-      run: |
-        set -e
+    # - name: Check if this is the first run on the branch
+    #   if: steps.changed-files.outputs.any_changed == 'false'
+    #   id: check-first-run
+    #   shell: bash
+    #   run: |
+    #     set -e
 
-        translations_path="${{ inputs.translations_path }}"
-        base_lang="${{ inputs.base_lang }}"
-        file_format="${{ inputs.file_format }}"
+    #     if git rev-parse "refs/tags/lokalise-upload-complete" >/dev/null 2>&1; then
+    #       echo "first_run=false" >> $GITHUB_OUTPUT
+    #     else
+    #       echo "first_run=true" >> $GITHUB_OUTPUT
+    #     fi
 
-        paths=()
-        while IFS= read -r path; do
-          path=$(echo "$path" | xargs)
-          if [ -n "$path" ]; then
-            if [ -d "${path}/${base_lang}" ]; then
-              paths+=("${path}/${base_lang}")
-            else
-              echo "Directory ${path}/${base_lang} does not exist."
-            fi
-          fi
-        done <<< "$translations_path"
+    # - name: Find all translation files
+    #   if: steps.changed-files.outputs.any_changed == 'false' && steps.check-first-run.outputs.first_run == 'true'
+    #   id: find-files
+    #   shell: bash
+    #   run: |
+    #     set -e
+
+    #     translations_path="${{ inputs.translations_path }}"
+    #     base_lang="${{ inputs.base_lang }}"
+    #     file_format="${{ inputs.file_format }}"
+
+    #     paths=()
+    #     while IFS= read -r path; do
+    #       path=$(echo "$path" | xargs)
+    #       if [ -n "$path" ]; then
+    #         if [ -d "${path}/${base_lang}" ]; then
+    #           paths+=("${path}/${base_lang}")
+    #         else
+    #           echo "Directory ${path}/${base_lang} does not exist."
+    #         fi
+    #       fi
+    #     done <<< "$translations_path"
     
-        if [ ${#paths[@]} -eq 0 ]; then
-          echo "No translation paths provided."
-          echo "has_files=false" >> $GITHUB_OUTPUT
-          exit 0
-        fi
+    #     if [ ${#paths[@]} -eq 0 ]; then
+    #       echo "No translation paths provided."
+    #       echo "has_files=false" >> $GITHUB_OUTPUT
+    #       exit 0
+    #     fi
     
-        mapfile -d '' -t ALL_FILES_ARRAY < <(find "${paths[@]}" -name "*.${file_format}" -type f -print0)
+    #     mapfile -d '' -t ALL_FILES_ARRAY < <(find "${paths[@]}" -name "*.${file_format}" -type f -print0)
 
-        if [ ${#ALL_FILES_ARRAY[@]} -eq 0 ]; then
-          echo "No translation files found."
-          echo "has_files=false" >> $GITHUB_OUTPUT
-        else
-          ALL_FILES=$(printf "%s," "${ALL_FILES_ARRAY[@]}")
-          ALL_FILES="${ALL_FILES%|}"
+    #     if [ ${#ALL_FILES_ARRAY[@]} -eq 0 ]; then
+    #       echo "No translation files found."
+    #       echo "has_files=false" >> $GITHUB_OUTPUT
+    #     else
+    #       ALL_FILES=$(printf "%s," "${ALL_FILES_ARRAY[@]}")
+    #       ALL_FILES="${ALL_FILES%|}"
           
-          echo "ALL_FILES=$ALL_FILES" >> $GITHUB_OUTPUT
-          echo "has_files=true" >> $GITHUB_OUTPUT
-        fi
+    #       echo "ALL_FILES=$ALL_FILES" >> $GITHUB_OUTPUT
+    #       echo "has_files=true" >> $GITHUB_OUTPUT
+    #     fi
 
-    - name: Install Lokalise CLI
-      if: steps.find-files.outputs.has_files == 'true' || steps.changed-files.outputs.any_changed == 'true'
-      shell: bash
-      run: |
-        set -e
-        chmod +x "${{ github.action_path }}/src/scripts/install_lokalise_cli.sh"
-        "${{ github.action_path }}/src/scripts/install_lokalise_cli.sh"
+    # - name: Install Lokalise CLI
+    #   if: steps.find-files.outputs.has_files == 'true' || steps.changed-files.outputs.any_changed == 'true'
+    #   shell: bash
+    #   run: |
+    #     set -e
+    #     chmod +x "${{ github.action_path }}/src/scripts/install_lokalise_cli.sh"
+    #     "${{ github.action_path }}/src/scripts/install_lokalise_cli.sh"
 
-    - name: Push translation files to Lokalise
-      if: steps.find-files.outputs.has_files == 'true' || steps.changed-files.outputs.any_changed == 'true'
-      shell: bash
-      env:
-        CLI_ADD_PARAMS: ${{ inputs.additional_params }}
-        MAX_RETRIES: ${{ inputs.max_retries }}
-        SLEEP_TIME: ${{ inputs.sleep_on_retry }}
-        BASE_LANG: ${{ inputs.base_lang }}
-      run: |
-        set -e
+    # - name: Push translation files to Lokalise
+    #   if: steps.find-files.outputs.has_files == 'true' || steps.changed-files.outputs.any_changed == 'true'
+    #   shell: bash
+    #   env:
+    #     CLI_ADD_PARAMS: ${{ inputs.additional_params }}
+    #     MAX_RETRIES: ${{ inputs.max_retries }}
+    #     SLEEP_TIME: ${{ inputs.sleep_on_retry }}
+    #     BASE_LANG: ${{ inputs.base_lang }}
+    #   run: |
+    #     set -e
 
-        if [ "${{ steps.check-first-run.outputs.first_run }}" == "true" ]; then
-          ALL_FILES="${{ steps.find-files.outputs.ALL_FILES }}"
-        else
-          ALL_CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
-        fi
+    #     if [ "${{ steps.check-first-run.outputs.first_run }}" == "true" ]; then
+    #       ALL_FILES="${{ steps.find-files.outputs.ALL_FILES }}"
+    #     else
+    #       ALL_CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
+    #     fi
 
-        if [ -z "${ALL_FILES}" ] && [ -z "${ALL_CHANGED_FILES}" ]; then
-          echo "No files to upload."
-          exit 0
-        fi
+    #     if [ -z "${ALL_FILES}" ] && [ -z "${ALL_CHANGED_FILES}" ]; then
+    #       echo "No files to upload."
+    #       exit 0
+    #     fi
         
-        chmod +x "${{ github.action_path }}/src/scripts/lokalise_upload.sh"
+    #     chmod +x "${{ github.action_path }}/src/scripts/lokalise_upload.sh"
 
-        set +e
-        echo "${ALL_FILES:-$ALL_CHANGED_FILES}" | tr ',' '\n' | xargs -P 6 -I {} bash "${{ github.action_path }}/src/scripts/lokalise_upload.sh" "{}" "${{ inputs.project_id }}" "${{ inputs.api_token }}"
-        xargs_exit_code=$?
-        set -e
+    #     set +e
+    #     echo "${ALL_FILES:-$ALL_CHANGED_FILES}" | tr ',' '\n' | xargs -P 6 -I {} bash "${{ github.action_path }}/src/scripts/lokalise_upload.sh" "{}" "${{ inputs.project_id }}" "${{ inputs.api_token }}"
+    #     xargs_exit_code=$?
+    #     set -e
 
-        if [ $xargs_exit_code -ne 0 ]; then
-          echo "File upload failed"
-          exit 1
-        fi
+    #     if [ $xargs_exit_code -ne 0 ]; then
+    #       echo "File upload failed"
+    #       exit 1
+    #     fi
 
-    - name: Mark Lokalise upload as complete
-      if: steps.check-first-run.outputs.first_run == 'true'
-      shell: bash
-      run: |
-        set -e
+    # - name: Mark Lokalise upload as complete
+    #   if: steps.check-first-run.outputs.first_run == 'true'
+    #   shell: bash
+    #   run: |
+    #     set -e
 
-        git config --global user.name "${GITHUB_ACTOR}"
-        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
-        if ! git rev-parse "refs/tags/lokalise-upload-complete" >/dev/null 2>&1; then
-          git tag -a "lokalise-upload-complete" -m "First Lokalise upload complete"
-          git push origin "lokalise-upload-complete"
-        else
-          echo "Tag 'lokalise-upload-complete' already exists."
-        fi
+    #     git config --global user.name "${GITHUB_ACTOR}"
+    #     git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
+    #     if ! git rev-parse "refs/tags/lokalise-upload-complete" >/dev/null 2>&1; then
+    #       git tag -a "lokalise-upload-complete" -m "First Lokalise upload complete"
+    #       git push origin "lokalise-upload-complete"
+    #     else
+    #       echo "Tag 'lokalise-upload-complete' already exists."
+    #     fi
